project:
  type: website

website:
  title: "Data science ramblings"
  site-url: https://www.stefanheyder.dev
  description: Blog
  navbar:
    right:
      - about.qmd
      - impressum.qmd
      - publications.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/stefanheyder
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
